#!/usr/bin/env bash
# Renders config/llm-systems.toml from LSM_* env vars. Sourced by both
# entrypoints. A bind-mounted (non-generated) TOML is left untouched.
set -euo pipefail

CFG="${LLM_SYSTEMS_CONFIG:-/opt/llm-systems-manager/config/llm-systems.toml}"
MARKER="# GENERATED by docker entrypoint — env-driven, edits are lost on restart"

render_config() {
  # A bind-mounted TOML always wins, even if it still carries the marker line.
  if grep -qsF " $CFG " /proc/self/mounts; then
    echo "[entrypoint] $CFG is bind-mounted — leaving as-is"
    return 0
  fi
  if [ -s "$CFG" ] && ! grep -qF "$MARKER" "$CFG"; then
    echo "[entrypoint] using mounted config at $CFG (not generated — leaving as-is)"
    return 0
  fi

  local influx_host="${LSM_INFLUX_HOST:-influxdb}"
  local influx_port="${LSM_INFLUX_PORT:-8086}"
  local influx_org="${LSM_INFLUX_ORG:-llm-systems-manager}"
  local influx_token="${LSM_INFLUX_TOKEN:-REPLACE_ME}"
  local ingest_token="${LSM_AE_INGEST_TOKEN:-REPLACE_ME}"
  local management_token="${LSM_AE_MANAGEMENT_TOKEN:-}"
  local ae_url="${LSM_ALARM_ENGINE_URL:-http://alarm-engine:8081}"
  local manager_url="${LSM_MANAGER_URL:-http://manager:5000}"
  local ae_tls="${LSM_AE_TLS_ENABLED:-true}"
  local cors="${LSM_CORS_ORIGINS:-http://localhost:5000}"
  local log_level="${LSM_LOG_LEVEL:-INFO}"
  local admin_user="${LSM_ADMIN_USER:-llmadmin}"
  # Default admin allowlist: loopback + private LAN ranges (172.16/12 covers
  # the docker bridge). Override with LSM_ADMIN_CIDRS.
  local admin_cidrs_csv="${LSM_ADMIN_CIDRS:-127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"

  for v in "$influx_token" "$ingest_token" "$management_token" "$admin_user" "$admin_cidrs_csv"; do
    case "$v" in
      *'"'*|*'\'*) echo "[entrypoint] ERROR: config values must not contain \" or \\" >&2; exit 1 ;;
    esac
  done

  local cidr_toml="" _oldifs="$IFS"
  IFS=','
  for c in $admin_cidrs_csv; do
    c="${c#"${c%%[![:space:]]*}"}"; c="${c%"${c##*[![:space:]]}"}"
    [ -n "$c" ] && cidr_toml="${cidr_toml}${cidr_toml:+, }\"$c\""
  done
  IFS="$_oldifs"

  cat > "$CFG" <<EOF
$MARKER

[manager]
alarm_engine_url = "$ae_url"
cors_origins = "$cors"
log_level = "$log_level"

[manager.auth]
username = "$admin_user"

[manager.security]
admin_cidrs = [$cidr_toml]

[alarm_engine]
manager_url = "$manager_url"
cors_origins = "$cors"
log_level = "$log_level"
ingest_token = "$ingest_token"
management_token = "$management_token"
tls_enabled = $ae_tls

[influxdb]
host = "$influx_host"
port = $influx_port
org  = "$influx_org"

[influxdb.tokens]
metrics        = "$influx_token"
metrics_rollup = "$influx_token"
admin          = "$influx_token"

[logging]
level = "$log_level"
EOF
  chmod 600 "$CFG"
  echo "[entrypoint] rendered $CFG from environment"
}
