#!/usr/bin/env bash
# Renders config/llm-systems.toml from LSM_* env vars. Sourced by both
# entrypoints. A bind-mounted (non-generated) TOML is left untouched.
set -euo pipefail

CFG="${LLM_SYSTEMS_CONFIG:-/opt/llm-systems-manager/config/llm-systems.toml}"
MARKER="# GENERATED by docker entrypoint — env-driven, edits are lost on restart"
# Generated alarm-engine tokens; lives in the ae-data volume both containers mount.
TOKEN_STORE="${LLM_SYSTEMS_AE_DATA:-/opt/llm-systems-manager/llm-systems-alarm-engine/data}/docker-tokens.env"

_new_token() { python3 -c 'import secrets; print(secrets.token_hex(32))'; }

# Fills AE_INGEST_TOKEN / AE_MANAGEMENT_TOKEN from .env, else from TOKEN_STORE,
# generating the store once (the first container to link it wins).
resolve_ae_tokens() {
  AE_INGEST_TOKEN="${LSM_AE_INGEST_TOKEN:-}"
  AE_MANAGEMENT_TOKEN="${LSM_AE_MANAGEMENT_TOKEN:-}"
  [ "$AE_INGEST_TOKEN" = "REPLACE_ME" ] && AE_INGEST_TOKEN=""
  [ "$AE_MANAGEMENT_TOKEN" = "REPLACE_ME" ] && AE_MANAGEMENT_TOKEN=""
  if [ -z "$AE_INGEST_TOKEN" ] || [ -z "$AE_MANAGEMENT_TOKEN" ]; then
    if [ ! -s "$TOKEN_STORE" ]; then
      mkdir -p "$(dirname "$TOKEN_STORE")"
      local tmp
      tmp="$(mktemp "$(dirname "$TOKEN_STORE")/.tokens.XXXXXX")"
      printf 'LSM_AE_INGEST_TOKEN=%s\nLSM_AE_MANAGEMENT_TOKEN=%s\n' "$(_new_token)" "$(_new_token)" > "$tmp"
      chmod 600 "$tmp"
      if ln "$tmp" "$TOKEN_STORE" 2>/dev/null; then
        echo "[entrypoint] alarm-engine token(s) not set in .env — generated once into $TOKEN_STORE"
        echo "[entrypoint]   read them with: docker compose exec alarm-engine cat $TOKEN_STORE"
        echo "[entrypoint]   agents use LSM_AE_INGEST_TOKEN; copy both into .env to pin them"
      fi
      rm -f "$tmp"
    fi
    [ -n "$AE_INGEST_TOKEN" ] || AE_INGEST_TOKEN="$(sed -n 's/^LSM_AE_INGEST_TOKEN=//p' "$TOKEN_STORE")"
    [ -n "$AE_MANAGEMENT_TOKEN" ] || AE_MANAGEMENT_TOKEN="$(sed -n 's/^LSM_AE_MANAGEMENT_TOKEN=//p' "$TOKEN_STORE")"
  fi
  if [ -z "$AE_INGEST_TOKEN" ] || [ -z "$AE_MANAGEMENT_TOKEN" ]; then
    echo "[entrypoint] ERROR: could not resolve the alarm-engine tokens (check $TOKEN_STORE)" >&2; exit 1
  fi
  if [ "$AE_INGEST_TOKEN" = "$AE_MANAGEMENT_TOKEN" ]; then
    echo "[entrypoint] ERROR: LSM_AE_MANAGEMENT_TOKEN must differ from LSM_AE_INGEST_TOKEN (agents hold the ingest token)" >&2; exit 1
  fi
}

render_config() {
  # A bind-mounted TOML always wins, even if it still carries the marker line.
  if grep -qsF " $CFG " /proc/self/mounts; then
    echo "[entrypoint] $CFG is bind-mounted — leaving as-is"
    return 0
  fi
  if [ -s "$CFG" ] && ! grep -qF "$MARKER" "$CFG"; then
    echo "[entrypoint] using mounted config at $CFG (not generated — leaving as-is)"
    return 0
  fi

  local influx_host="${LSM_INFLUX_HOST:-influxdb}"
  local influx_port="${LSM_INFLUX_PORT:-8086}"
  local influx_org="${LSM_INFLUX_ORG:-llm-systems-manager}"
  local influx_token="${LSM_INFLUX_TOKEN:-REPLACE_ME}"
  resolve_ae_tokens
  local ingest_token="$AE_INGEST_TOKEN"
  local management_token="$AE_MANAGEMENT_TOKEN"
  local ae_url="${LSM_ALARM_ENGINE_URL:-http://alarm-engine:8081}"
  local manager_url="${LSM_MANAGER_URL:-http://manager:5000}"
  local ae_tls="${LSM_AE_TLS_ENABLED:-true}"
  local cors="${LSM_CORS_ORIGINS:-http://localhost:5000}"
  local log_level="${LSM_LOG_LEVEL:-INFO}"
  local admin_user="${LSM_ADMIN_USER:-llmadmin}"
  # Default admin allowlist: loopback + private LAN ranges (172.16/12 covers
  # the docker bridge). Override with LSM_ADMIN_CIDRS.
  local admin_cidrs_csv="${LSM_ADMIN_CIDRS:-127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}"
  # Externally-reachable host(s) agents dial; added to the manager cert SAN.
  local public_hosts_csv="${LSM_MANAGER_PUBLIC_HOST:-}"
  local smtp_server="${LSM_SMTP_SERVER:-}"
  local smtp_port="${LSM_SMTP_PORT:-587}"
  local smtp_user="${LSM_SMTP_USER:-}"
  local smtp_password="${LSM_SMTP_PASSWORD:-}"
  local discord_webhook="${LSM_DISCORD_WEBHOOK_URL:-}"

  for v in "$influx_token" "$ingest_token" "$management_token" "$admin_user" \
           "$admin_cidrs_csv" "$public_hosts_csv" "$smtp_server" "$smtp_user" \
           "$smtp_password" "$discord_webhook"; do
    case "$v" in
      *'"'*|*'\'*) echo "[entrypoint] ERROR: config values must not contain \" or \\" >&2; exit 1 ;;
    esac
  done
  case "$smtp_port" in
    ''|*[!0-9]*) echo "[entrypoint] ERROR: LSM_SMTP_PORT must be numeric" >&2; exit 1 ;;
  esac

  local _oldifs="$IFS"
  local cidr_toml=""
  IFS=','
  for c in $admin_cidrs_csv; do
    c="${c#"${c%%[![:space:]]*}"}"; c="${c%"${c##*[![:space:]]}"}"
    [ -n "$c" ] && cidr_toml="${cidr_toml}${cidr_toml:+, }\"$c\""
  done
  local hosts_toml=""
  for c in $public_hosts_csv; do
    c="${c#"${c%%[![:space:]]*}"}"; c="${c%"${c##*[![:space:]]}"}"
    [ -n "$c" ] && hosts_toml="${hosts_toml}${hosts_toml:+, }\"$c\""
  done
  IFS="$_oldifs"

  cat > "$CFG" <<EOF
$MARKER

[manager]
alarm_engine_url = "$ae_url"
log_level = "$log_level"
public_hosts = [$hosts_toml]

[manager.auth]
username = "$admin_user"

[manager.security]
admin_cidrs = [$cidr_toml]

[manager.proxies]
# "auto" = tab appears when an approved agent advertises the capability.
llm_chat  = "auto"
openclaw  = "auto"
image_gen = "auto"

[alarm_engine]
manager_url = "$manager_url"
cors_origins = "$cors"
log_level = "$log_level"
ingest_token = "$ingest_token"
management_token = "$management_token"
tls_enabled = $ae_tls

[influxdb]
host = "$influx_host"
port = $influx_port
org  = "$influx_org"

[influxdb.tokens]
metrics        = "$influx_token"
metrics_rollup = "$influx_token"
admin          = "$influx_token"

[logging]
level = "$log_level"
EOF

  # Notification channels are only written when supplied — otherwise the
  # defaults (example.com placeholders) would look configured but not work.
  if [ -n "$smtp_server" ]; then
    cat >> "$CFG" <<EOF

[notifications.smtp]
server   = "$smtp_server"
port     = $smtp_port
user     = "$smtp_user"
password = "$smtp_password"
EOF
  fi
  if [ -n "$discord_webhook" ]; then
    cat >> "$CFG" <<EOF

[notifications.discord]
webhook_url = "$discord_webhook"
EOF
  fi

  # Adds the https twin of each http origin in [alarm_engine].cors_origins.
  local fixed
  if fixed="$(python3 "$(dirname "${BASH_SOURCE[0]}")/../tools/installer/toml_reconcile.py" \
                origins "$CFG" "" 0 2>/dev/null)" && [ -n "$fixed" ]; then
    printf '%s\n' "$fixed" > "$CFG"
  fi

  chmod 600 "$CFG"
  echo "[entrypoint] rendered $CFG from environment"
}
